### PR TITLE
docs: Add links to wiki for release process

### PR DESCRIPTION
**Pull request by Xuanwo**

### CODE REVIEW

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
This PR fails CI. I also think that adding this uncontextualised link is not that helpful. Our contrib docs are in GitHub. We can argue that they should move but the release guide is a very specialised doc aimed at a small fraction of the (P)PMC. Even in the most active of Apache communities, the number of release managers is tiny compared to the full size of the community. Even using the GitHub wiki is a short term solution - I mean to move them to cwiki.apache.org but Confluence is a real pain and I'm focusing on higher priority work.

**Review by pjfanning — CHANGES_REQUESTED** [review]
Failed CI and generally, I don't support this change.

**Comment by mdedetrich** [comment]
> I mean to move them to cwiki.apache.org but Confluence is a real pain and I'm focusing on higher priority work.

iirc We had a community discussion on this and the preference was to actually host these information on github wiki, not confluence and it was also said there was no rule that forces us to host this content on confluence.

The only requirement was needing to document where it is, thats all.

**Comment by Xuanwo** [comment]
Makes sense, let's close this PR.

**Pull request closed without merging**
