### PR TITLE
Updating static assets for main branch

### PR DESCRIPTION
**Pull request by samueleresca**
See: https://github.com/apache/incubator-pekko-sbt-paradox/issues/84

- Moving assets folder from incubator-pekko-sbt-theme to incubator-pekko-site
- Updating content directory.
- Targeting `main`

Change tested in:

- https://github.com/apache/incubator-pekko-site/pull/49
- https://github.com/apache/incubator-pekko-site/pull/51
- https://github.com/apache/incubator-pekko-site/pull/52

Next steps:

- Rebase main into `asf-site` for deploying changes

### CODE REVIEW

**Comment by pjfanning** [comment]
Before merging this, I'd like to look at testing a repo like incubator-pekko. I can do that locally. Presumably, if I use the latest snapshot of pekko-sbt-paradox and set the asset.hostname to pekko.staged.apache.org - that I should get a usable set of pages.

If this works out, we can merge this. We can then reset the asf-staging branch to match main.

**Comment by pjfanning** [comment]
I built pekko-http docs locally with pekko-sbt-paradox 1.0.0+9-1bc182b6-SNAPSHOT and there was an issue with the Java/Scala tabs. On the CORS page, I get this:

image

This should be displayed with 2 tabs - one for Scala, one for Java.

**Comment by pjfanning** [comment]
apologies - that CORS page is already broken - see https://pekko.apache.org/docs/pekko-http/current/common/cors.html

I'm still a bit confused by the output when I build the pekko-http docs because the static artifacts all seem to be in the target folder. Does the sbt-paradox tool download them from the static site and copy them locally?

**Comment by samueleresca** [comment]
> apologies - that CORS page is already broken - see https://pekko.apache.org/docs/pekko-http/current/common/cors.html
> 
> I'm still a bit confused by the output when I build the pekko-http docs because the static artifacts all seem to be in the target folder. Does the sbt-paradox tool download them from the static site and copy them locally?

@pjfanning sbt-paradox include the files in the `target` folder as they are created under the default `_template` route (see [Create local template](https://developer.lightbend.com/docs/paradox/current/customization/theming.html#create-local-templates).

These files are then copied over in the `content` folder and deployed in the CDN

**Comment by pjfanning** [comment]
I'm not saying it is a bad idea to copy the files during the build but it is also theoretically possible to just link to the full URLs so that we don't deploy multiple copies of the static files (one set per git repo). Is this something that could be considered? I agree that both approaches have pros and cons.

**Comment by samueleresca** [comment]
> I'm not saying it is a bad idea to copy the files during the build but it is also theoretically possible to just link to the full URLs so that we don't deploy multiple copies of the static files (one set per git repo). Is this something that could be considered? I agree that both approaches have pros and cons.

Yes, I think that's possible. At the moment I only moved the static assets defined in `pekko-sbt-paradox` repostiory. There is a whole set of assets that are defined in [paradox-material-theme](https://github.com/jonas/paradox-material-theme).

I have double checked in `incubator-pekko-http` by updating `pekko-sbt-paradox` version: `1.0.0+10-9676045b-SNAPSHOT` and I'm seeing the following asset sub-tree in the `target` folder:

```
assets
│   ├── fonts
│   │   ├── font-awesome.css
│   │   ├── material-icons.css
│   │   └── specimen
│   │       ├── FontAwesome.ttf
│   │       ├── FontAwesome.woff
│   │       ├── FontAwesome.woff2
│   │       ├── MaterialIcons-Regular.ttf
│   │       ├── MaterialIcons-Regular.woff
│   │       └── MaterialIcons-Regular.woff2
│   ├── images
│   │   └── favicon.png
│   ├── javascripts
│   │   ├── application.583bbe55.js
│   │   ├── modernizr.1aa3b519.js
│   │   └── paradox-material-theme.js
│   └── stylesheets
│       ├── application-palette.22915126.css
│       ├── application.451f80e5.css
│       └── paradox-material-theme.css
```

If I use the `1.0.0` (at the moment in main) of `pekko-sbt-paradox`, the sub-tree in the `target` folder is:

```
assets
│   ├── fonts
│   │   ├── font-awesome.css
│   │   ├── material-icons.css
│   │   └── specimen
│   │       ├── FontAwesome.ttf
│   │       ├── FontAwesome.woff
│   │       ├── FontAwesome.woff2
│   │       ├── MaterialIcons-Regular.ttf
│   │       ├── MaterialIcons-Regular.woff
│   │       └── MaterialIcons-Regular.woff2
│   ├── images
│   │   ├── apache-incubator.svg
│   │   ├── favicon.png
│   │   ├── pekko_favicon.png
│   │   └── pekko_logo.png
│   ├── javascripts
│   │   ├── application.583bbe55.js
│   │   ├── groups.js
│   │   ├── modernizr.1aa3b519.js
│   │   └── paradox-material-theme.js
│   └── stylesheets
│       ├── application-palette.22915126.css
│       ├── application.451f80e5.css
│       ├── paradox-material-theme.css
│       └── pekko-theme.css
```

Note that only the following assets are defined in `pekko-sbt-paradox`:

- `pekko-theme.css`
- `groups.js` `paradox-material-theme.js` (already present in `paradox-material-theme`, but overwritten in `incubator-pekko-site`)
- `apache-incubator.svg`, `pekko_favicon.png`, `pekko_logo.png`

While the other assets are coming from the material theme: [paradox-material-theme](https://github.com/jonas/paradox-material-theme). 

Since the [paradox-material-theme](https://github.com/jonas/paradox-material-theme) is no longer maintained, I think it makes sense to plan to merge it into `incubator-pekko-sbt-paradox` / `incubator-pekko-site`. See also the discussion in: https://github.com/apache/incubator-pekko-sbt-paradox/issues/34

So I'm seeing some options here:

- (Done in this PR) Move to the CDN the pekko-customized assets. These assets are the ones that we will most likely edit for styling purposes.
- Move the other `paradox-material-theme` assets into `incubator-pekko-site`. This would allow to move faster in case we want to fully diverge from the `paradox-material-theme` style in future.

Let me know if I'm missing something.

**Review by pjfanning — APPROVED** [review]
lgtm

**Review by mdedetrich — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
@samueleresca I recreated asf-staging from main branch - losing the forked history. If you need to preserve anything from that forked history then it would be good if you could create a branch on your samueleresca fork of this repo.

**Pull request merged**
