### PR TITLE
simple paradox-based homepage setup

### PR DESCRIPTION
**Pull request by jrudolph**
Should we try to create the homepage with paradox as well? This is an early attempt to set it up.

### CODE REVIEW

**Comment by mdedetrich** [comment]
> Should we try to create the homepage with paradox as well? This is an early attempt to set it up.

Not entirely sure on this, I asked around on this and was suggested different tools which are better suited to micro sites such as https://github.com/47degrees/sbt-microsites or https://github.com/planet42/Laika

**Comment by pjfanning** [comment]
I would favour using the same Paradox based setup. We get the same look and feel and it's easier for the maintainers to get used to just one tool.

**Comment by jrudolph** [comment]
I think we should either use:
 * paradox for the look and feel (but which will need more customizations to get what we want)
 * jekyll (because it is a standard for these kind of tasks and allows easy creation of blog entries)
 * any of the standard Apache choices for consistency

**Comment by mdedetrich** [comment]
> jekyll (because it is a standard for these kind of tasks and allows easy creation of blog entries)

On this point, sbt-microsite wraps around jekyll. It just provides an easy to use sbt-wrapper so it can easily be integrated within an sbt project.

Laika is a complete reimplementation of microsite concept.

> any of the standard Apache choices for consistency

@Claudenw mentioned https://infra.apache.org/asf-pelican.html that is typically used by Apache projects. My personal rebuttal here is that while it may be familiar for Apache projects, it would also be completely unfamiliar with typical Pekko contributors.

I personally like to keep the set of technologies/build tools used within a project to a minimum so I would either use Paradox or investigate sbt-microsite (since it also wraps Jekyll). My only somewhat minor qualm about Paradox is it seems to be suited/designed for docs generated from software projects rather than microsites but I have nothing against it for now.

**Comment by mdedetrich** [comment]
It does sound like we should discuss this on the mailing list however since once tech stacks get chosen they tend to stick

**Comment by mdedetrich** [comment]
Mailing list thread created at https://lists.apache.org/thread/fthn305vphk7l61gsldm2jyon7q7tz4w

**Comment by pjfanning** [comment]
This is related to https://github.com/apache/incubator-pekko-site/issues/3

**Comment by pjfanning** [comment]
@jrudolph can we merge this? I can add follow on PRs that provide a bit more content.

**Pull request merged**
