### PR TITLE
fix link of pekko-sample-distributed-workers-scala

### LINKED ISSUE #93: link of pekko-sample-distributed-data-workers-scala is 404
the link of pekko-sample-distributed-data-workers-scala is 404
https://pekko.apache.org/docs/pekko-samples/current/pekko-sample-distributed-data-workers-scala/

### PR DESCRIPTION
**Pull request by laglangyue**
close #93

### CODE REVIEW

**Review by Roiocam — APPROVED** [review]
LGTM

**Review by Roiocam — CHANGES_REQUESTED** [review]
need to locally build and update the content folder.

**Comment by laglangyue** [comment]
> need to locally build and update the content folder.

done

**Review by He-Pin — APPROVED** [review]
Lgtm, thanks

**Review by Roiocam — APPROVED** [review]
LGTM, Thanks

**Comment by pjfanning** [comment]
deployed - thanks

**Pull request merged**
